### ISSUE TITLE
new configs set trees on fire

### ISSUE THREAD

**Issue by Unionhawk** [AnAverageHuman/Echoreply-Configs#1]
![This is what you have created](http://i.imgur.com/FwTVUC8.jpg)

**Comment by AnAverageHuman** [comment]
Fixed in [3b4c881](https://github.com/AnAverageHuman/Echoreply-Configs/commit/3b4c881b1cd105af04023df8b967e01ec655202f).

**Comment by IeuanK** [comment]
What even was this
